config/routes.rb
Rails.application.routes.draw do
  resources :pop_sessions
  resources :pop_channels
  resources :ledgers
  resources :accounts
  root to: 'accounts#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
end

app/models/pop_channel.rb
class PopChannel < ApplicationRecord
  belongs_to :ledger
end

app/controllers/pop_channels_controller.rb
class PopChannelsController < ApplicationController
  before_action :set_pop_channel, only: [:show, :edit, :update, :destroy]

  # GET /pop_channels
  # GET /pop_channels.json
  def index
    @pop_channels = PopChannel.all
  end

  # GET /pop_channels/1
  # GET /pop_channels/1.json
  def show
  end

  # GET /pop_channels/new
  def new
    @pop_channel = PopChannel.new
  end

  # GET /pop_channels/1/edit
  def edit
  end

  # POST /pop_channels
  # POST /pop_channels.json
  def create
    @pop_channel = PopChannel.new(pop_channel_params)

    respond_to do |format|
      if @pop_channel.save
        format.html { redirect_to @pop_channel, notice: 'Pop channel was successfully created.' }
        format.json { render :show, status: :created, location: @pop_channel }
      else
        format.html { render :new }
        format.json { render json: @pop_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pop_channels/1
  # PATCH/PUT /pop_channels/1.json
  def update
    respond_to do |format|
      if @pop_channel.update(pop_channel_params)
        format.html { redirect_to @pop_channel, notice: 'Pop channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @pop_channel }
      else
        format.html { render :edit }
        format.json { render json: @pop_channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pop_channels/1
  # DELETE /pop_channels/1.json
  def destroy
    @pop_channel.destroy
    respond_to do |format|
      format.html { redirect_to pop_channels_url, notice: 'Pop channel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pop_channel
      @pop_channel = PopChannel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pop_channel_params
      params.require(:pop_channel).permit(:ledger_id, :time, :address, :poptx, :nonce, :popchannel_url)
    end
end

app/helpers/pop_channels_helper.rb
module PopChannelsHelper
end

app/views/pop_channels/_form.html.erb
<%= form_with(model: pop_channel, local: true) do |form| %>
  <% if pop_channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pop_channel.errors.count, "error") %> prohibited this pop_channel from being saved:</h2>

      <ul>
      <% pop_channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ledger_id %>
    <%= form.number_field :ledger_id %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :poptx %>
    <%= form.text_field :poptx %>
  </div>

  <div class="field">
    <%= form.label :nonce %>
    <%= form.text_field :nonce %>
  </div>

  <div class="field">
    <%= form.label :popchannel_url %>
    <%= form.text_field :popchannel_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pop_channels/edit.html.erb
<h1>Editing Pop Channel</h1>

<%= render 'form', pop_channel: @pop_channel %>

<%= link_to 'Show', @pop_channel %> |
<%= link_to 'Back', pop_channels_path %>

app/views/pop_channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pop Channels</h1>

<table>
  <thead>
    <tr>
      <th>Ledger</th>
      <th>Time</th>
      <th>Address</th>
      <th>Poptx</th>
      <th>Nonce</th>
      <th>Popchannel url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pop_channels.each do |pop_channel| %>
      <tr>
        <td><%= pop_channel.ledger_id %></td>
        <td><%= pop_channel.time %></td>
        <td><%= pop_channel.address %></td>
        <td><%= pop_channel.poptx %></td>
        <td><%= pop_channel.nonce %></td>
        <td><%= pop_channel.popchannel_url %></td>
        <td><%= link_to 'Show', pop_channel %></td>
        <td><%= link_to 'Edit', edit_pop_channel_path(pop_channel) %></td>
        <td><%= link_to 'Destroy', pop_channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pop Channel', new_pop_channel_path %>

app/views/pop_channels/new.html.erb
<h1>New Pop Channel</h1>

<%= render 'form', pop_channel: @pop_channel %>

<%= link_to 'Back', pop_channels_path %>

app/views/pop_channels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ledger:</strong>
  <%= @pop_channel.ledger_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @pop_channel.time %>
</p>

<p>
  <strong>Address:</strong>
  <%= @pop_channel.address %>
</p>

<p>
  <strong>Poptx:</strong>
  <%= @pop_channel.poptx %>
</p>

<p>
  <strong>Nonce:</strong>
  <%= @pop_channel.nonce %>
</p>

<p>
  <strong>Popchannel url:</strong>
  <%= @pop_channel.popchannel_url %>
</p>

<%= link_to 'Edit', edit_pop_channel_path(@pop_channel) %> |
<%= link_to 'Back', pop_channels_path %>