config/routes.rb
Rails.application.routes.draw do
  resources :pop_sessions
  resources :pop_channels
  resources :ledgers
  resources :accounts
  root to: 'accounts#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
end

app/models/ledger.rb
class Ledger < ApplicationRecord
  belongs_to :account
  has_many :pop_sessions
  has_many :pop_channels
end

app/controllers/Ledgers_controller.rb
# coding: utf-8                                                                                                                
class LedgersController < ApplicationController
  before_action :set_Ledger, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /Ledgers                                                                                                                  
  # GET /Ledgers.json                                                                                                             
  def index
    @Ledgers = Ledger.all
  end

  # GET /Ledgers/1                                                                                                                
  # GET /Ledgers/1.json                                                                                                           
  def show
  end

  # GET /Ledgers/new                                                                                                              
  def new
    # 残高を調べる                                                                                                             
    @balance=bitcoinRPC('getreceivedbyaddress',[params[:send_address]])
    # ワレットIDを送付                                                                                                         
    @params=params
    @Ledger = Ledger.new
  end

  # GET /Ledgers/1/edit                                                                                                           
  def edit
  end

  # POST /Ledgers                                                                                                                 
  # POST /Ledgers.json                                                                                                            
  def create
    @Ledger = Ledger.new(Ledger_params)

    respond_to do |format|
      if @Ledger.save
        format.html { redirect_to @Ledger, notice: 'Ledger was successfully created.' }
        format.json { render :show, status: :created, location: @Ledger }
      else
        format.html { render :new }
        format.json { render json: @Ledger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Ledgers/1                                                                                                          
  # PATCH/PUT /Ledgers/1.json                                                                                                     
  def update
    respond_to do |format|
      if @Ledger.update(Ledger_params)
        format.html { redirect_to @Ledger, notice: 'Ledger was successfully updated.' }
        format.json { render :show, status: :ok, location: @Ledger }
      else
        format.html { render :edit }
        format.json { render json: @Ledger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Ledgers/1                                                                                                             
  # DELETE /Ledgers/1.json                                                                                                        
  def destroy
    @Ledger.destroy
    respond_to do |format|
      format.html { redirect_to Ledgers_url, notice: 'Ledger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.                                                      
    def set_Ledger
      @Ledger = Ledger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.                                       
    def Ledger_params
      params.require(:Ledger).permit(:Account_id, :send_address, :receive_address, :amoount, :fee, :balance)
    end
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/views/ledgers/_form.html.erb
<%= form_with(model: ledger, local: true) do |form| %>
  <% if ledger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ledger.errors.count, "error") %> prohibited this ledger from being¥
 saved:</h2>

      <ul>
      <% ledger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :account_id %>
    <% account=Account.find(current_user.id) %>
    <%= account.account_name %>
    <%= form.hidden_field :account_id, value: account.id %>
  </div>

  <div class="field">
    <%= form.label :direction %>
    <%= "send" %>
    <%= form.hidden_field :direction, value: "send" %>
  </div>

  <div class="field">
    <%= form.label :from %>
    <%= account.address%>
    <%= form.hidden_field :from, value: account.address %>
  </div>

  <div class="field">
    <%= form.label :to %>
    <%= form.text_field :to %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">

    <%= form.hidden_field :txid, value: "" %>
  </div>

  <div class="field">

    <%= form.hidden_field :tx, value: "" %>
  </div>

  <div class="actions">
     <%= form.submit("送金", class: 'btn btn-primary') %>
  </div>
<% end %>

app/views/ledgers/edit.html.erb
<h1>Editing Ledger</h1>

<%= render 'form', ledger: @ledger %>

<%= link_to 'Show', @ledger %> |
<%= link_to 'Back', ledgers_path %>

app/views/ledgers/index.html.erb
<p id="notice"><%= notice %></p>
<% account=Account.find(current_user.id) %>
<h2>オンチェーント取引一覧</h2>
<h3>アカウント名：<%= account.account_name %></h3>

<%= link_to '送金', new_ledger_path, class: 'btn btn-primary' %>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th ></th>
      <th>from</th>
      <th>To</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    <% @Ledgers.each do |ledger| %>
      <tr>
        <td><%= link_to 'PoP開始', pop_sessions_path(ledger) %></td>
	<td><%= ledger.from %></td>
        <td><%= ledger.to %></td>
	<td><%= ledger.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Ledger', new_ledger_path %>

app/views/ledgers/new.html.erb
<p id="notice"><%= notice %></p>
<% account=Account.find(current_user.id) %>
<h1><%= account.account_name %> Ledgers</h1>

<%= link_to '送金', new_ledger_path, class: 'btn btn-primary' %>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th ></th>
      <th>To</th>
      <th>Amount</th>
    </tr>
  </thead>

  <tbody>
    <% @Ledger.each do |ledger| %>
      <tr>
        <td><%= link_to 'PoPセッション', pop_sessions_path(ledger) %></td>
	<td><%= ledger.to %></td>
	<td><%= ledger.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/ledgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @ledger.account_id %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @ledger.direction %>
</p>

<p>
  <strong>From:</strong>
  <%= @ledger.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @ledger.to %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @ledger.amount %>
</p>

<p>
  <strong>Txid:</strong>
  <%= @ledger.txid %>
</p>

<p>
  <strong>Tx:</strong>
  <%= @ledger.tx %>
</p>

<%= link_to '送金一覧', ledgers_path, class: 'btn btn-primary' %>