config/routes.rb
Rails.application.routes.draw do
  resources :pop_sessions
  resources :pop_channels
  resources :ledgers
  resources :accounts
  root to: 'accounts#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
end

app/models/pop_session.rb
class PopSession < ApplicationRecord
  belongs_to :ledger
end

app/controllers/pop_sessions_controller.rb
class PopSessionsController < ApplicationController
  before_action :set_pop_session, only: [:show, :edit, :update, :destroy]

  # GET /pop_sessions
  # GET /pop_sessions.json
  def index
    @pop_sessions = PopSession.all
  end

  # GET /pop_sessions/1
  # GET /pop_sessions/1.json
  def show
  end

  # GET /pop_sessions/new
  def new
    @pop_session = PopSession.new
  end

  # GET /pop_sessions/1/edit
  def edit
  end

  # POST /pop_sessions
  # POST /pop_sessions.json
  def create
    @pop_session = PopSession.new(pop_session_params)

    respond_to do |format|
      if @pop_session.save
        format.html { redirect_to @pop_session, notice: 'Pop session was successfully created.' }
        format.json { render :show, status: :created, location: @pop_session }
      else
        format.html { render :new }
        format.json { render json: @pop_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pop_sessions/1
  # PATCH/PUT /pop_sessions/1.json
  def update
    respond_to do |format|
      if @pop_session.update(pop_session_params)
        format.html { redirect_to @pop_session, notice: 'Pop session was successfully updated.' }
        format.json { render :show, status: :ok, location: @pop_session }
      else
        format.html { render :edit }
        format.json { render json: @pop_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pop_sessions/1
  # DELETE /pop_sessions/1.json
  def destroy
    @pop_session.destroy
    respond_to do |format|
      format.html { redirect_to pop_sessions_url, notice: 'Pop session was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pop_session
      @pop_session = PopSession.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pop_session_params
      params.require(:pop_session).permit(:ledger_id, :time, :address, :poptx, :nonce, :popchannel_url)
    end
end

app/helpers/pop_sessions_helper.rb
module PopSessionsHelper
end

app/views/pop_sessions/_form.html.erb
<%= form_with(model: pop_session, local: true) do |form| %>
  <% if pop_session.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pop_session.errors.count, "error") %> prohibited this pop_session from being saved:</h2>

      <ul>
      <% pop_session.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ledger_id %>
    <%= form.number_field :ledger_id %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :poptx %>
    <%= form.text_field :poptx %>
  </div>

  <div class="field">
    <%= form.label :nonce %>
    <%= form.text_field :nonce %>
  </div>

  <div class="field">
    <%= form.label :popchannel_url %>
    <%= form.text_field :popchannel_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pop_sessions/edit.html.erb
<h1>Editing Pop Session</h1>

<%= render 'form', pop_session: @pop_session %>

<%= link_to 'Show', @pop_session %> |
<%= link_to 'Back', pop_sessions_path %>

app/views/pop_sessions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pop Sessions</h1>

<table>
  <thead>
    <tr>
      <th>Ledger</th>
      <th>Time</th>
      <th>Address</th>
      <th>Poptx</th>
      <th>Nonce</th>
      <th>Popchannel url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pop_sessions.each do |pop_session| %>
      <tr>
        <td><%= pop_session.ledger_id %></td>
        <td><%= pop_session.time %></td>
        <td><%= pop_session.address %></td>
        <td><%= pop_session.poptx %></td>
        <td><%= pop_session.nonce %></td>
        <td><%= pop_session.popchannel_url %></td>
        <td><%= link_to 'Show', pop_session %></td>
        <td><%= link_to 'Edit', edit_pop_session_path(pop_session) %></td>
        <td><%= link_to 'Destroy', pop_session, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pop Session', new_pop_session_path %>

app/views/pop_sessions/new.html.erb
<h1>New Pop Session</h1>

<%= render 'form', pop_session: @pop_session %>

<%= link_to 'Back', pop_sessions_path %>

app/views/pop_sessions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ledger:</strong>
  <%= @pop_session.ledger_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @pop_session.time %>
</p>

<p>
  <strong>Address:</strong>
  <%= @pop_session.address %>
</p>

<p>
  <strong>Poptx:</strong>
  <%= @pop_session.poptx %>
</p>

<p>
  <strong>Nonce:</strong>
  <%= @pop_session.nonce %>
</p>

<p>
  <strong>Popchannel url:</strong>
  <%= @pop_session.popchannel_url %>
</p>

<%= link_to 'Edit', edit_pop_session_path(@pop_session) %> |
<%= link_to 'Back', pop_sessions_path %>