config/routes.rb
Rails.application.routes.draw do
  resources :pop_sessions
  resources :pop_channels
  resources :ledgers
  resources :accounts
  root to: 'accounts#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html  
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :ledgers
end

app/controllers/accounts_controller.rb
# coding: utf-8

class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # ログインフィルター                                                                                                                 
  before_action :authenticate_user!, only: [:new, :show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:user_id, :entity_type, :account_name, :address, :balance)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= current_user.id %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= form.label :entity_type %>
    <%= form.select :entity_type,["user","service"] %>
  </div>

  <div class="field">
    <%= form.label :account_name %>
    <%= form.text_field :account_name %>
  </div>

  <div class="field">
    <%= form.hidden_field :address, value: "" %>
  </div>

  <div class="field">
    <%= form.hidden_field :balance, value: 0.0 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<%= link_to 'New Account', new_account_path, class: 'btn btn-primary' %>

<table  class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Entity type</th>
      <th>Account name</th>
      <th>Address</th>
      <th>Balance</th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to 'Show', account %></td>
        <td><%= account.entity_type %></td>
        <td><%= account.account_name %></td>
        <td><%= account.address %></td>
        <td><%= account.balance %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>
<%= @account_params %>
<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<p>
  <strong>Entity type:</strong>
  <%= @account.entity_type %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @account.account_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @account.address %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @account.balance %>
</p>

<%= link_to '台帳', ledgers_path(@account), class: 'btn btn-primary' %>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>